server:
  port: 8080

spring:
  datasource:
    hikari:
      maximum-pool-size: 5
    url: jdbc:mysql://flowforms.cnsyswq0g0tx.sa-east-1.rds.amazonaws.com/anamnesys
    username: flowformsadmin
    password: 741852Pca!
    driver-class-name: com.mysql.cj.jdbc.Driver
    cache:
      type: caffeine

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: agendahub.service@gmail.com
    password: yyja eraf opiw vark
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jackson:
    time-zone: "America/Sao_Paulo"  # Ajuste do fuso horário

  data:
    jpa:
      properties:
        hibernate.jdbc.time_zone: "America/Sao_Paulo"  # Ajuste do fuso horário no Hibernate

form:
  base:
    url: https://flowforms.com.br/

websocket:
  endpoint:
    url: ws://api.flowforms.com.br/ws

management:
  endpoints:
    web:
      exposure:
        include: health
