version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_anamnesys
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: anamnesys
      MYSQL_USER: k2k2
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:

